### ISSUE TITLE
HTMLElement have children[] even when empty?

### ISSUE THREAD

**Issue by gillyspy** [medicomp/eslint-html-parser#9]
be nice if the children property was always set on an HTMLElement. 
being undefined is a bit weird.  

Otherwise, this simple parser is doing well for our use-case.  

any ideas on how to tell eslint to highlight the entire element and not just the first bracket?

**Comment by lstratman** [comment]
Excellent suggestion, I've done that for both children and attributes.  Version 6.8.2 is now up in the registry.

As for highlighting the entire element, just report using the `loc: node.loc`:

```js
context.report({
    loc: node.loc,
    message: 'HTML text chunks must be set with ${i18n.stringId}'
});
```

While the CLI formatters for ESLint will never emit the range for the error, just the starting location, if your IDE uses the ESLint engine internally (like Visual Studio or VSCode) then it will highlight the entire node for the error:

![image](https://user-images.githubusercontent.com/24588/160860778-e8269300-ab02-4a22-807d-3571856f9078.png)
